# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://junza.top:3306/cloudbox
    url: jdbc:mysql://localhost:3306/cloudbox

  devtools:
    restart:
      #设置开启热部署
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:templates/,classpath:static/
#      static-locations: classpath:templates/,classpath:static/,file:/www/local/,file:D:/runtime/cloudbox
  #文件上传
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
#    邮箱验证
  mail:
    host: smtp.163.com
    username: cloudbox2022@163.com
    password: SLQHNJQFZKPYAHWJ

server:
  servlet:
    context-path: /cloudbox
  port: 8181
#错误信息
  error:
    include-message: always
    include-stacktrace: always

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.lj.cloudbox.pojo

pagehelper:
  #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true

settings:
  root: D:/runtime/cloudbox/files
  space: 2G

