# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://liujun666.xyz:3306/cloudbox
  devtools:
    restart:
      enabled: true  #设置开启热部署
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:templates/,classpath:static/,file:/www/local/,file:D:/runtime/cloudbox
server:
  servlet:
    context-path: /cloudbox
  port: 8181
#错误信息
  error:
    include-message: always
    include-stacktrace: always

pagehelper:
  reasonable: true #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
